#!/usr/bin/env bash

REVEAL_PORT=${PORT:-37777}
echo "Presentation will be available at http://localhost:${REVEAL_PORT}/slides.md"
./node_modules/reveal-md/bin/reveal-md.js slides.md --port ${REVEAL_PORT} --disable-auto-open $@
